resource_group_name = "my_terraform_jk"
resource_group_location = "West Europe"
virtual_network_name = "vnetprod-jk"
subnet_name = "subnet-jk"
public_ip_name = "publicip-jk"
network_security_group_name = "nsgprod-jk"
network_interface_name = "nicprod-jk"
linux_virtual_machine_name = "ubuntu-bionic-jk"